### ISSUE TITLE
Injection not working

### ISSUE THREAD

**Issue by 1gravity** [FunnyDevs/hilt-conductor#2]
I followed your instructions but nothing is injected. I have a simple Module:
```
@Module
@InstallIn(ControllerComponent::class)
object HiltModule {
    @Provides
    fun provideLogger(): Logger {
        return LoggerImpl(true)
    }
}
```
The controller is simple too
```
@ConductorEntryPoint
class MatchesController : BaseController() {
    @Inject
    lateinit var logger: Logger
```
When the app runs it crashes with
`kotlin.UninitializedPropertyAccessException: lateinit property logger has not been initialized`

Am I doing something wrong?

**Comment by 1gravity** [comment]
Ok so your readme misses the part where you add your plugin to the Gradle script...

**Comment by FunnyDevs** [comment]
Look at the step 2

```
Step 2. Apply plugin in application module of build.gradle.

plugins {
    ...
    id 'dagger.hilt.android.plugin'
}
```

**Comment by 1gravity** [comment]
> Look at the step 2
> 
> ```
> Step 2. Apply plugin in application module of build.gradle.
> 
> plugins {
>     ...
>     id 'dagger.hilt.android.plugin'
> }
> ```

Yes, that's the Hilt plugin but you also need your funnydev plugin. 
```
plugins {
    id("com.funnydevs.hilt-conductor.plugin")
    id("dagger.hilt.android.plugin")
}
```

**Comment by FunnyDevs** [comment]
Ah, you are right, i have confused dagger plugin with my own :D.  I will update it immediately

**Comment by 1gravity** [comment]
> Ah, you are right, i have confused dagger plugin with my own :D. I will update it immediately
Thank you for writing the plugin btw. I really appreciate it. I still like Controllers better than Fragments ;-)

**Comment by FunnyDevs** [comment]
me too, i hate Fragments!
As soon as i have time, i'll implement the  @Named qualifier handling
