### ISSUE TITLE
Cause: no such class: com.example.hiltexample2.MainControllerHiltInterface

### ISSUE THREAD

**Issue by TikTak123** [FunnyDevs/hilt-conductor#7]
Here is the project where you can see this exception https://github.com/TikTak123/Hilt-Playground

**Comment by TikTak123** [comment]
Can you say please, when you can fixed it?

**Comment by FunnyDevs** [comment]
Have you tried the 0.4.3 version?

**Comment by TikTak123** [comment]
tried, same

**Comment by FunnyDevs** [comment]
I have seen the repository you linked here, but isn't it my example app ? i will try next days to take a look

**Comment by TikTak123** [comment]
Yes, this is your example code. I first tried it on my project and after it didn't work. I thought maybe I'm doing something wrong and then I decided to run it on a small project and result was same.

**Comment by FunnyDevs** [comment]
Sorry, it was my fault: i removed the "injection" from the MainController and, without it, the HiltInterface is not created
So, add the field to be injected as this one

```
@ConductorEntryPoint
class MainController(args: Bundle?) : Controller(args) {

    @Inject
    @Named("first")
    lateinit var text: String

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup, savedViewState: Bundle?): View {
        return inflater.inflate(R.layout.controller_main, container, false)
    }
}
```

**Comment by TikTak123** [comment]
thanks, everything works great.
